### ISSUE TITLE
23.12.11: pytest fails in two unit

### ISSUE THREAD

**Issue by kloczek** [pycountry/pycountry#190]
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using 'installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

<details>
<summary>Here is pytest output:</summary>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pycountry-23.12.11-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pycountry-23.12.11-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network'
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.18, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pycountry-23.12.11
configfile: pytest.ini
collected 48 items

src/pycountry/tests/test_general.py ..............F.................F...............                                                                                                  [100%]

========================================================================================= FAILURES ==========================================================================================
_______________________________________________________________________________________ test_locales ________________________________________________________________________________________
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.8/site-packages/_pytest/python.py", line 1797, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/_pytest/python.py", line 199, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/home/tkloczko/rpmbuild/BUILD/pycountry-23.12.11/src/pycountry/tests/test_general.py", line 179, in test_locales
    german = gettext.translation(
  File "/usr/lib64/python3.8/gettext.py", line 588, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'iso_3166-1'
_______________________________________________________________________________ test_no_results_lookup_error ________________________________________________________________________________
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.8/site-packages/_pytest/python.py", line 1797, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/_pytest/python.py", line 199, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/home/tkloczko/rpmbuild/BUILD/pycountry-23.12.11/src/pycountry/tests/test_general.py", line 343, in test_no_results_lookup_error
    DATABASE_DIR = resource_filename("pycountry", "databases")
  File "/home/tkloczko/rpmbuild/BUILD/pycountry-23.12.11/src/pycountry/tests/test_general.py", line 340, in resource_filename
    importlib_resources.files(package_or_requirement) / resource_name
AttributeError: module 'importlib.resources' has no attribute 'files'
===================================================================================== warnings summary ======================================================================================
src/pycountry/tests/test_general.py::test_missing_common_official_use_same
  /home/tkloczko/rpmbuild/BUILDROOT/python-pycountry-23.12.11-2.fc35.x86_64/usr/lib/python3.8/site-packages/pycountry/db.py:51: UserWarning: Country's official_name not found. Country name provided instead.
    warnings.warn(warning_message, UserWarning)

src/pycountry/tests/test_general.py::test_missing_common_official_use_same
  /home/tkloczko/rpmbuild/BUILDROOT/python-pycountry-23.12.11-2.fc35.x86_64/usr/lib/python3.8/site-packages/pycountry/db.py:51: UserWarning: Country's common_name not found. Country name provided instead.
    warnings.warn(warning_message, UserWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
------------------------------------------------------ generated xml file: /home/tkloczko/rpmbuild/BUILD/pycountry-23.12.11/report.xml ------------------------------------------------------
================================================================================== short test summary info ==================================================================================
FAILED src/pycountry/tests/test_general.py::test_locales - FileNotFoundError: [Errno 2] No translation file found for domain: 'iso_3166-1'
FAILED src/pycountry/tests/test_general.py::test_no_results_lookup_error - AttributeError: module 'importlib.resources' has no attribute 'files'
========================================================================= 2 failed, 46 passed, 2 warnings in 0.52s ==========================================================================
```
</details>

<details>
<summary>List of installed modules in build env:</summary>

```console
Package            Version
------------------ -------
build              1.0.3
cppclean           0.13
distro             1.8.0
dnf                4.18.2
exceptiongroup     1.1.3
gpg                1.23.2
importlib-metadata 7.0.0
iniconfig          2.0.0
installer          0.7.0
libdnf             0.72.0
packaging          23.2
pluggy             1.3.0
poetry-core        1.8.1
pyproject_hooks    1.0.0
pytest             7.4.3
python-dateutil    2.8.2
six                1.16.0
tomli              2.0.1
wheel              0.42.0
zipp               3.17.0
```
</details>

Please let me know if you need more details or want me to perform some diagnostics.

**Comment by kloczek** [comment]
Just found that ` src/pycountry/tests/test_general.py::test_locales` fail is result of fedora patch (will fix that so you can ignore that unit fail) however second one looks like it is real.

**Comment by nschimmoller** [comment]
@zware or @ctheune going to tag you in here for expert opinion 😅

**Comment by zware** [comment]
@kloczek `importlib_resources>=5.12.0` is required on Python 3.8.

**Comment by nschimmoller** [comment]
@kloczek does @zware 's comment resolve your question / issue?

**Comment by kloczek** [comment]
> @kloczek does @zware 's comment resolve your question / issue?

Yes it solved.
Closing.
