### ISSUE TITLE
23.12.11: pytest fails in 4 units

### ISSUE THREAD

**Issue by kloczek** [pycountry/pycountry#220]
After move to python 3.9 and pytest 8.1.1 now I have 3 new failing units.
<details>
<summary>Here is pytest output:</summary>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pycountry-23.12.11-2.fc36.x86_64/usr/lib64/python3.9/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pycountry-23.12.11-2.fc36.x86_64/usr/lib/python3.9/site-packages
+ /usr/bin/pytest -ra -m 'not network' --deselect src/pycountry/tests/test_general.py::test_no_results_lookup_error
============================= test session starts ==============================
platform linux -- Python 3.9.18, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pycountry-23.12.11
configfile: pytest.ini
collected 48 items / 1 deselected / 47 selected

src/pycountry/tests/test_general.py .......FF.....F......F.............. [ 76%]
...........                                                              [100%]

=================================== FAILURES ===================================
____________________ test_subdivisions_directly_accessible _____________________
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 340, in from_call
    result: Optional[TResult] = func()
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 240, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/threadexception.py", line 87, in pytest_runtest_call
    yield from thread_exception_runtest_hook()
  File "/usr/lib/python3.9/site-packages/_pytest/threadexception.py", line 63, in thread_exception_runtest_hook
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 90, in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
  File "/usr/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 65, in unraisable_exception_runtest_hook
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/logging.py", line 849, in pytest_runtest_call
    yield from self._runtest_for(item, "call")
  File "/usr/lib/python3.9/site-packages/_pytest/logging.py", line 832, in _runtest_for
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/capture.py", line 883, in pytest_runtest_call
    return (yield)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/skipping.py", line 256, in pytest_runtest_call
    return (yield)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 182, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 172, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 1777, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 200, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/home/tkloczko/rpmbuild/BUILD/pycountry-23.12.11/src/pycountry/tests/test_general.py", line 104, in test_subdivisions_directly_accessible
    assert len(pycountry.subdivisions) == 5127
AssertionError: assert 5046 == 5127
 +  where 5046 = len(<pycountry.Subdivisions object at 0x7f967a2cc8b0>)
 +    where <pycountry.Subdivisions object at 0x7f967a2cc8b0> = pycountry.subdivisions
_________________ test_subdivisions_have_subdivision_as_parent _________________
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 340, in from_call
    result: Optional[TResult] = func()
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 240, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/threadexception.py", line 87, in pytest_runtest_call
    yield from thread_exception_runtest_hook()
  File "/usr/lib/python3.9/site-packages/_pytest/threadexception.py", line 63, in thread_exception_runtest_hook
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 90, in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
  File "/usr/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 65, in unraisable_exception_runtest_hook
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/logging.py", line 849, in pytest_runtest_call
    yield from self._runtest_for(item, "call")
  File "/usr/lib/python3.9/site-packages/_pytest/logging.py", line 832, in _runtest_for
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/capture.py", line 883, in pytest_runtest_call
    return (yield)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/skipping.py", line 256, in pytest_runtest_call
    return (yield)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 182, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 172, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 1777, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 200, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/home/tkloczko/rpmbuild/BUILD/pycountry-23.12.11/src/pycountry/tests/test_general.py", line 121, in test_subdivisions_have_subdivision_as_parent
    assert fr_01.parent_code == "FR-ARA"
AssertionError: assert 'FR-FR-ARA' == 'FR-ARA'

  - FR-ARA
  + FR-FR-ARA
  ? +++
_________________________________ test_locales _________________________________
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 340, in from_call
    result: Optional[TResult] = func()
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 240, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/threadexception.py", line 87, in pytest_runtest_call
    yield from thread_exception_runtest_hook()
  File "/usr/lib/python3.9/site-packages/_pytest/threadexception.py", line 63, in thread_exception_runtest_hook
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 90, in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
  File "/usr/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 65, in unraisable_exception_runtest_hook
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/logging.py", line 849, in pytest_runtest_call
    yield from self._runtest_for(item, "call")
  File "/usr/lib/python3.9/site-packages/_pytest/logging.py", line 832, in _runtest_for
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/capture.py", line 883, in pytest_runtest_call
    return (yield)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/skipping.py", line 256, in pytest_runtest_call
    return (yield)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 182, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 172, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 1777, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 200, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/home/tkloczko/rpmbuild/BUILD/pycountry-23.12.11/src/pycountry/tests/test_general.py", line 179, in test_locales
    german = gettext.translation(
  File "/usr/lib64/python3.9/gettext.py", line 592, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'iso_3166-1'
___________________________ test_subdivision_parent ____________________________
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 340, in from_call
    result: Optional[TResult] = func()
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 240, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/threadexception.py", line 87, in pytest_runtest_call
    yield from thread_exception_runtest_hook()
  File "/usr/lib/python3.9/site-packages/_pytest/threadexception.py", line 63, in thread_exception_runtest_hook
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 90, in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
  File "/usr/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 65, in unraisable_exception_runtest_hook
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/logging.py", line 849, in pytest_runtest_call
    yield from self._runtest_for(item, "call")
  File "/usr/lib/python3.9/site-packages/_pytest/logging.py", line 832, in _runtest_for
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/capture.py", line 883, in pytest_runtest_call
    return (yield)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/skipping.py", line 256, in pytest_runtest_call
    return (yield)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 182, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 172, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 1777, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 200, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/home/tkloczko/rpmbuild/BUILD/pycountry-23.12.11/src/pycountry/tests/test_general.py", line 267, in test_subdivision_parent
    assert sd.parent_code == "CV-B"
AssertionError: assert 'CV-CV-B' == 'CV-B'

  - CV-B
  + CV-CV-B
=============================== warnings summary ===============================
src/pycountry/tests/test_general.py::test_missing_common_official_use_same
  /home/tkloczko/rpmbuild/BUILDROOT/python-pycountry-23.12.11-2.fc36.x86_64/usr/lib/python3.9/site-packages/pycountry/db.py:52: UserWarning: Country's official_name not found. Country name provided instead.
    warnings.warn(warning_message, UserWarning)

src/pycountry/tests/test_general.py::test_missing_common_official_use_same
  /home/tkloczko/rpmbuild/BUILDROOT/python-pycountry-23.12.11-2.fc36.x86_64/usr/lib/python3.9/site-packages/pycountry/db.py:52: UserWarning: Country's common_name not found. Country name provided instead.
    warnings.warn(warning_message, UserWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated xml file: /home/tkloczko/rpmbuild/BUILD/pycountry-23.12.11/report.xml -
=========================== short test summary info ============================
FAILED src/pycountry/tests/test_general.py::test_subdivisions_directly_accessible
FAILED src/pycountry/tests/test_general.py::test_subdivisions_have_subdivision_as_parent
FAILED src/pycountry/tests/test_general.py::test_locales - FileNotFoundError:...
FAILED src/pycountry/tests/test_general.py::test_subdivision_parent - Asserti...
============ 4 failed, 43 passed, 1 deselected, 2 warnings in 0.54s ============
```
</details>

**Comment by zware** [comment]
I can't reproduce this failure. Does it still occur with current dependencies and data?

**Comment by kloczek** [comment]
I'm using as source input aurtogenerated from git version tag tar ball. So that is about current data.
About dependencies here i list of installed modules in build env:
```console
Package            Version
------------------ -----------
build              1.2.1
exceptiongroup     1.1.3
fastjsonschema     2.19.1
importlib_metadata 7.1.0
iniconfig          2.0.0
installer          0.7.0
lark               1.1.9
packaging          24.0
pluggy             1.4.0
poetry-core        1.9.0
pyproject_hooks    1.0.0
pytest             8.1.1
python-dateutil    2.9.0.post0
tokenize_rt        5.2.0
tomli              2.0.1
wheel              0.43.0
zipp               3.18.1
```

**Comment by zware** [comment]
All tests are currently passing everywhere I can run them.

**Comment by kloczek** [comment]
OK so what could be possible cause of those fails? 🤔

**Comment by zware** [comment]
I don't know.  Those failures look to me like a mismatch between the code and the data.
