### ISSUE TITLE
subdivisions.search_fuzzy does not match english spellings of subdivisions

### ISSUE THREAD

**Issue by anna-parker** [pycountry/pycountry#243]
Hi! Thank you for this great library! I am trying to use `pycountry` to curate data from the INSDC.

I have the problem that subdivisions in the INSDC use the official(?) English equivalent. For example `Lombardy, Italy` instead of `Lombardia, Italy`. `Xinjiang Uygur Autonomous Region, China` instead of `Xinjiang Uygur Zizhiqu, China`. I was trying to use search_fuzzy to match these cases but it sadly does not recognize the English equivalents.

```
pycountry.subdivisions.search_fuzzy('Xinjiang Uygur Autonomous Region')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aparker/micromamba/envs/loculus-ingest/lib/python3.12/site-packages/pycountry/__init__.py", line 273, in search_fuzzy
    raise LookupError(query)
LookupError: xinjiang uygur autonomous region
```

I have now implemented a work-around were I use the `fuzzywuzzy` library and additionally remove subdivision-specific words (such as region, state, province etc.) from my input strings. However, this doesn't catch all cases.

It would be great if `pycountry` could also fuzzy match on these known English equivalents - especially cases where the difference lies with a subdivision-specific word translation (e.g. Zizhiqu = Autonomous region).

**Comment by nschimmoller** [comment]
As you mentioned this is a data limitation. ISO 3166-2 uses local language names for subdivisions, so the Italian region is listed as "Lombardia" (Italian), not "Lombardy" (English):

```python 
lombardia = pycountry.subdivisions.get(code="IT-25")
print(lombardia.name)  # "Lombardia"

# To find it:
pycountry.subdivisions.search_fuzzy("Lombardia")  # ✓
pycountry.subdivisions.get(code="IT-25")  # ✓
pycountry.subdivisions.lookup("Lombardia")  # ✓
```

pycountry reflects the official ISO data, which uses local names. English translations would require a separate localization system. I think there is a desire to add this at some point but not currently in the development roadmap.
